silly_jokes = [
    'Why did the tomato turn red? Because it saw the salad dressing!',
    'What do you call a fake noodle? An impasta.',
    'What did the grape say when it got stepped on? Nothing, it just let out a little wine.',
    'Why did the scarecrow win an award? Because he was outstanding in his field.',
    'Why did the bicycle fall over? Because it was two-tired.',
    'Why dont scientists trust atoms? Because they make up everything.',
    'Why couldnt the bicycle stand up by itself? Because it was two-tired.',
    'Why was the math book sad? Because it had too many problems.',
    'What did one toilet say to the other toilet? You look flushed.',
    'What do you call a fake noodle? An impasta.',
    'Why did the coffee file a police report? It got mugged.',
    'Why did the orange stop rolling down the hill? It ran out of juice.',
    'What do you call a sleeping bull? A bulldozer.',
    'Why did the hipster burn his tongue? He drank his coffee before it was cool.',
    'Why did the computer go to the doctor? Because it had a virus.',
    'What do you call a boomerang that doesnt come back? A stick.',
    'Why did the banana go to the doctor? Because it wasnt peeling well.',
    'Why dont skeletons fight each other? They dont have the guts.',
    'Why did the chicken cross the playground? To get to the other slide.',
    'What did the grape say when it got stepped on? Nothing, it just let out a little wine.',
    'Why did the cookie go to the doctor? Because it was feeling crummy.',
    'Why couldnt the bicycle stand up by itself? Because it was two-tired.',
    'Why was the math book sad? Because it had too many problems.',
    'What do you call a pile of cats? A meowtain.',
    'Why was the sand wet? Because the sea weed.',
    'Why dont ghosts use elevators? Because they lift their spirits.',
    'What do you call a bear with no teeth? A gummy bear.',
    'Why dont dinosaurs drive cars? They are extinct.',
    'Why was the belt sent to jail? For holding up pants.',
    'What do you call an alligator in a vest? An investi-gator!',
    'Why did the ghost go to the bar? For the boos.',
    'What do you call a can opener that doesnt work? A cant opener.',
    'Why did the tomato turn red? Because it saw the salad dressing!',
    'Why did the dog sit in the shade? Because he didnt want to be a hot dog.',
    'Why did the math book look so sad? Because it had too many problems.',
    'Why dont seagulls fly by the bay? Because then they would be bagels.',
    'Why dont eggs tell jokes? Because they would crack each other up.',
    'What do you call a sleeping dinosaur? A dino-snore.',
    'Why dont scientists trust atoms? Because they make up everything.',
    'Why dont ants get sick? Because they have tiny ant-bodies.',
    'Why did the cookie go to the doctor? Because it was feeling crummy.',
]
