motivational_songs =[
    'Eye of the Tiger - Survivor',
    'Lose Yourself - Eminem',
    'The Climb - Miley Cyrus',
    'Stronger - Kanye West',
    'Hall of Fame - The Script ft. Will.I.Am',
    'I Will Survive - Gloria Gaynor',
    'Unstoppable - Sia',
    'Rise Up - Andra Day',
    'Dont Stop Believin - Journey',
    'Beautiful Day - U2',
    'Dream On - Aerosmith',
    'What a Wonderful World - Louis Armstrong',
    'We Are the Champions - Queen',
    'Man in the Mirror - Michael Jackson',
    'I Believe I Can Fly - R. Kelly',
    'Believe - Cher',
    'Shake It Off - Taylor Swift',
    'Its My Life - Bon Jovi',
    'Dont Stop - Fleetwood Mac',
    'Aint No Mountain High Enough - Marvin Gaye and Tammi Terrell',
    'Aint No Stoppin Us Now - McFadden and Whitehead',
    'Survivor - Destinys Child',
    'Im Still Standing - Elton John',
    'I Will Always Love You - Whitney Houston',
    'Brave - Sara Bareilles',
    'Just Like Fire - Pink',
    'Happy - Pharrell Williams',
    'Cant Hold Us - Macklemore and Ryan Lewis',
    'Lose My Breath - Destinys Child',
    'The Power of Love - Celine Dion',
    'Walking on Sunshine - Katrina and the Waves',
    'Hold On - Wilson Phillips',
    'Live Your Life - T.I. ft. Rihanna',
    'Fighter - Christina Aguilera',
    'Skyscraper - Demi Lovato',
    'All I Do Is Win - DJ Khaled ft. T-Pain, Ludacris, Snoop Dogg and Rick Ross',
    'Beautiful - Christina Aguilera',
    'Confident - Demi Lovato',
    'Stronger Than You Think - Fireflight',
    'Unwritten - Natasha Bedingfield',
    'Everybodys Free (To Wear Sunscreen) - Baz Luhrmann',
    'Lose Control - Missy Elliott ft. Ciara and Fatman Scoop',
    'Dont Give Up - Peter Gabriel ft. Kate Bush',
    'We Will Rock You - Queen',
    'Time of Our Lives - Pitbull ft. Ne-Yo',
    'Cant Stop - Red Hot Chili Peppers',
    'Eye On It - TobyMac',
    'Pumped Up Kicks - Foster the People',
    'Youre Beautiful - James Blunt',
    'My Way - Frank Sinatra'
]

comfort_lofi_songs=[
    'SLOW DANCING IN THE DARK - by joji',
    'TEST DRIVE - by joji',
    'WANTED U - by joji',
    'ATTENTION - by joji',
    'CANT GET OVER YOU - by joji',
    'Star shopping - lil peep',
    '9 to 5 - CHRIS RAIN',
    'Dance with me - Shiloh Dynasty',
    'Ill keep you safe - Shiloh Dynasty',
    'Crashing down - Redrose',
    'Sweet Jane - Playyard',
    'heaven come - Josh Golden',
    'lovely - by Billie Eilish & Khalid',
    'death bed (coffee for your head) - by Powfu ft. beabadoobee',
    'Dancing in the Dark - by Joji',
    'idontwannabeyouanymore - by Billie Eilish',
    'Mariposa - by Peach Tree Rascals',
    'Say You Love Me - by Jessie Ware',
    'Sinking - by Jazmine Sullivan',
    'I Dont Want to Wait - by The Belle Game',
    'Tired - by Alan Walker ft. Gavin James',
    'Shiver - by Lucy Rose',
    'Golden - by Harry Styles',
    'Circles - by Mac Miller',
    'Nostalgia - by Aso',
    'I Want You Around - by Snoh Aalegra',
    'The River - by Axel Flóvent',
    'Daffodils - by Kevin Verwijmeren',
    'Something About Us - by Daft Punk',
    'Moon River - by Frank Ocean',
    'Stay - by Rihanna ft. Mikky Ekko',
    'Not About Angels - by Birdy',
]