encouragement_messages = [
    "You're doing great!",
    "Hang in there!",
    "Keep up the good work!",
    "Believe in yourself and all that you are.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "Every day is a new opportunity to achieve greatness.",
    "Be fearless in the pursuit of what sets your soul on fire.",
    "Don't let yesterday take up too much of today.",
    "Dream big and don't be afraid to fail.",
    "You are never too old to set a new goal or dream a new dream.",
    "Your attitude determines your direction.",
    "You are braver than you believe, stronger than you seem, and smarter than you think.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "The best way to predict the future is to create it.",
    "You don't have to be great to start, but you have to start to be great.",
    "Difficult roads often lead to beautiful destinations.",
    "You are not a drop in the ocean, you are the entire ocean in a drop.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "You are never too small to make a difference.",
    "Believe you can and you're halfway there.",
    "Chase your dreams and never look back.",
    "In the middle of every difficulty lies opportunity.",
    "The only way to have a good day is to start it with a positive attitude.",
    "You are the architect of your own destiny.",
    "Happiness is not something ready-made. It comes from your own actions.",
    "Your only limit is the amount of doubt you have in yourself.",
    "The only time you should ever look back is to see how far you've come.",
]